# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip-tools

before_script:
  - (cd requirements; make rq_clean requirements)
  - pip install -e '.[develop]'

# command to run tests, e.g. python setup.py test
script:
  - tox
